import { createHash } from 'crypto'

export type EventContractPdfInput = {
  storeName: string
  storeEmail?: string
  storePhone?: string
  eventTitle: string
  eventCode?: string
  eventDate?: string
  eventTime?: string
  venue?: string
  clientName: string
  clientEmail: string
  revision: number
  serviceAgreement: string
  scopeOfWork: string
  paymentTerms: string
  cancellationPolicy: string
  signerName?: string
  signerEmail?: string
  signatureText?: string
  signedAt?: string
}

export function hashPublicContractToken(token: string) {
  return createHash('sha256').update(token).digest('hex')
}

export function normalizeSignatureText(value: string) {
  return value
    .normalize('NFKD')
    .replace(/[\u0300-\u036f]/g, '')
    .replace(/[^A-Za-z0-9]+/g, ' ')
    .trim()
    .toLowerCase()
    .replace(/\s+/g, ' ')
}

export function signatureMatchesSigner(signerName: string, signatureText: string) {
  const signer = normalizeSignatureText(signerName)
  const signature = normalizeSignatureText(signatureText)
  return signer.length >= 2 && signer === signature
}

function ascii(value: string) {
  return value
    .replace(/[\u2018\u2019]/g, "'")
    .replace(/[\u201C\u201D]/g, '"')
    .replace(/[\u2013\u2014]/g, '-')
    .replace(/\u2022/g, '-')
    .replace(/[^\x20-\x7E]/g, '?')
}

function escapePdfText(value: string) {
  return ascii(value)
    .replace(/\\/g, '\\\\')
    .replace(/\(/g, '\\(')
    .replace(/\)/g, '\\)')
}

function wrapLine(value: string, width = 86) {
  const clean = value.replace(/\s+/g, ' ').trim()
  if (!clean) return ['']
  const words = clean.split(' ')
  const lines: string[] = []
  let line = ''
  for (const word of words) {
    const candidate = line ? `${line} ${word}` : word
    if (candidate.length <= width) {
      line = candidate
      continue
    }
    if (line) lines.push(line)
    if (word.length <= width) {
      line = word
      continue
    }
    for (let cursor = 0; cursor < word.length; cursor += width) {
      const part = word.slice(cursor, cursor + width)
      if (part.length === width || cursor + width < word.length) lines.push(part)
      else line = part
    }
  }
  if (line) lines.push(line)
  return lines
}

function section(lines: string[], title: string, value: string) {
  lines.push('')
  lines.push(title.toUpperCase())
  lines.push(...wrapLine(value || 'Not specified.'))
}

function contractLines(input: EventContractPdfInput) {
  const lines: string[] = [
    input.storeName || 'Sedifex Store',
    input.storeEmail || '',
    input.storePhone || '',
    '',
    'EVENT SERVICE AGREEMENT',
    `Revision ${Math.max(1, Math.floor(input.revision || 1))}`,
    '',
    `Event: ${input.eventTitle || 'Event'}`,
    input.eventCode ? `Reference: ${input.eventCode}` : '',
    input.eventDate ? `Date: ${input.eventDate}${input.eventTime ? ` at ${input.eventTime}` : ''}` : '',
    input.venue ? `Venue: ${input.venue}` : '',
    `Client: ${input.clientName || 'Client'}`,
    input.clientEmail ? `Client email: ${input.clientEmail}` : '',
  ].filter((value, index) => Boolean(value) || index === 3 || index === 6)

  section(lines, 'Service agreement', input.serviceAgreement)
  section(lines, 'Scope of work', input.scopeOfWork)
  section(lines, 'Payment terms', input.paymentTerms)
  section(lines, 'Cancellation / refund policy', input.cancellationPolicy)

  lines.push('')
  lines.push('E-SIGNATURE RECORD')
  if (input.signedAt && input.signatureText) {
    lines.push(`Signer: ${input.signerName || 'Client'}`)
    if (input.signerEmail) lines.push(`Signer email: ${input.signerEmail}`)
    lines.push(`Typed signature: ${input.signatureText}`)
    lines.push(`Signed at: ${input.signedAt}`)
    lines.push('Consent: Electronic signature consent recorded in Sedifex.')
  } else {
    lines.push('Status: Awaiting client signature.')
  }
  lines.push('')
  lines.push('Generated by Sedifex. Keep this document with the event approval record.')
  return lines
}

export function buildEventContractPdf(input: EventContractPdfInput): Buffer {
  const sourceLines = contractLines(input)
  const wrapped = sourceLines.flatMap(line => line ? wrapLine(line) : [''])
  const linesPerPage = 43
  const pages: string[][] = []
  for (let index = 0; index < wrapped.length; index += linesPerPage) {
    pages.push(wrapped.slice(index, index + linesPerPage))
  }
  if (!pages.length) pages.push(['Event service agreement'])

  const pageCount = pages.length
  const fontObjectId = 3 + pageCount * 2
  const pageObjectIds = pages.map((_, index) => 3 + index * 2)
  const contentObjectIds = pages.map((_, index) => 4 + index * 2)
  const objectMap = new Map<number, Buffer>()

  objectMap.set(1, Buffer.from('<< /Type /Catalog /Pages 2 0 R >>'))
  objectMap.set(2, Buffer.from(`<< /Type /Pages /Kids [${pageObjectIds.map(id => `${id} 0 R`).join(' ')}] /Count ${pageCount} >>`))

  pages.forEach((pageLines, index) => {
    const commands: string[] = ['BT', '/F1 11 Tf', '54 760 Td']
    pageLines.forEach((line, lineIndex) => {
      if (lineIndex === 0 && index === 0) commands.push('/F1 16 Tf')
      commands.push(`(${escapePdfText(line)}) Tj`)
      if (lineIndex === 0 && index === 0) commands.push('/F1 11 Tf')
      if (lineIndex < pageLines.length - 1) commands.push('0 -16 Td')
    })
    commands.push('ET')
    const stream = Buffer.from(`${commands.join('\n')}\n`)
    objectMap.set(pageObjectIds[index], Buffer.from(`<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Contents ${contentObjectIds[index]} 0 R /Resources << /Font << /F1 ${fontObjectId} 0 R >> >> >>`))
    objectMap.set(contentObjectIds[index], Buffer.concat([
      Buffer.from(`<< /Length ${stream.length} >>\nstream\n`),
      stream,
      Buffer.from('endstream'),
    ]))
  })
  objectMap.set(fontObjectId, Buffer.from('<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>'))

  const header = Buffer.from('%PDF-1.4\n')
  const parts: Buffer[] = [header]
  const offsets: number[] = [0]
  let offset = header.length
  for (let id = 1; id <= fontObjectId; id += 1) {
    offsets[id] = offset
    const body = objectMap.get(id) ?? Buffer.from('<<>>')
    const object = Buffer.concat([Buffer.from(`${id} 0 obj\n`), body, Buffer.from('\nendobj\n')])
    parts.push(object)
    offset += object.length
  }

  const xrefOffset = offset
  const xrefLines = [`xref`, `0 ${fontObjectId + 1}`, '0000000000 65535 f ']
  for (let id = 1; id <= fontObjectId; id += 1) {
    xrefLines.push(`${String(offsets[id]).padStart(10, '0')} 00000 n `)
  }
  const trailer = Buffer.from(`${xrefLines.join('\n')}\ntrailer\n<< /Size ${fontObjectId + 1} /Root 1 0 R >>\nstartxref\n${xrefOffset}\n%%EOF`)
  parts.push(trailer)
  return Buffer.concat(parts)
}
